INSERT INTO DMS (KTOV, KOL, CENA, SORT,ZID)
	SELECT DISTINCT KTOV, KOL, CENA, SORT,
	(SELECT TOP 1 s.ZID FROM DMS s WHERE s.ZID = (SELECT MAX(z.ZID) FROM DMS z))
	FROM DMS t WHERE t.KTOV IN 
	(
		SELECT DISTINCT s.KTOV FROM DMS s WHERE 
		s.ZID = (SELECT MIN(z.ZID) FROM DMS z) AND s.KTOV NOT IN 
		(
			SELECT DISTINCT s.KTOV FROM DMS s WHERE s.ZID = (SELECT MAX(z.ZID) FROM DMS z)
		)
	)